#include <atomic>
#include "ctagSoundProcessor.hpp"

#include "daisysp.h"
#include "Drums/analogbassdrum.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDaisySP : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            ctagSoundProcessorDaisySP();
            virtual ~ctagSoundProcessorDaisySP();

        private:
            virtual void knowYourself() override;

            daisysp::AnalogBassDrum bd;

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
	atomic<int32_t> test, cv_test;
	atomic<int32_t> trigger, trig_trigger;
	// sectionHpp
        };
    }
}