name: tbd-sim-tapp-tbd4vcv-linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libgl-dev
          wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.bz2
          tar --bzip2 -xf boost_1_77_0.tar.bz2
          cd boost_1_77_0
          ./bootstrap.sh
          ./b2 cxxflags=-fPIC cflags=-fPIC --with-program_options --with-system --with-filesystem --with-thread -a threading=multi link=static
          cd ..
          wget https://vcvrack.com/downloads/Rack-SDK-2.0.0-lin.zip
          unzip Rack-SDK-2.0.0-lin.zip
      - name: Build
        run: |
          cd tapp
          mkdir build
          cd build
          cmake -DBOOST_ROOT=/home/runner/work/ctag-tbd/ctag-tbd/boost_1_77_0 ..
          make
          cpack
          cd ../..
          cd simulator
          mkdir build
          cd build
          cmake -DBOOST_ROOT=/home/runner/work/ctag-tbd/ctag-tbd/boost_1_77_0 ..
          make
          cpack
          cd ../..
          cd tbd4vcv
          mkdir build
          cd build
          export RACK_DIR=/home/runner/work/ctag-tbd/ctag-tbd/Rack-SDK
          cmake -DBOOST_ROOT=/home/runner/work/ctag-tbd/ctag-tbd/boost_1_77_0 ..
          make
          cpack
          cd ../..
      - name: Archive binaries
        run: |
          zip --junk-paths binaries tapp/build/*.zip simulator/build/*.zip tbd4vcv/build/*.zip
      - name: Upload binary
        uses: actions/upload-artifact@v2.2.1
        with:
          name: binaries.zip
          # A file, directory or wildcard pattern that describes what to upload
          path: binaries.zip