name: tbd4vcv-win

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-ninja mingw-w64-x86_64-boost mingw-w64-x86_64-cmake unzip zip
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./tbd4vcv/cibuild-win-msys2mingw-win64.sh
      - name: Upload binary
        uses: actions/upload-artifact@v2.2.1
        with:
          name: tbd4vcv-blob.zip
          # A file, directory or wildcard pattern that describes what to upload
          path: ./tbd4vcv/build/tbd4vcv-2.0.0-win64.zip